<?php
/* 
 * Generated by CRUDigniter v3.2 
 * www.crudigniter.com
 */
 
class Test_model extends MY_Model
{
    function __construct()
    {
        parent::__construct();
    }

    
    /*
     * Get subject by id
     */
     function get_student_count()
     {

        ##will improve
        $this->db->select('debit,id as ids');
       // $this->db->where('class_id',);
     $query=$this->db->get('account_transaction')->result();
      return $query;

}

function templatetest($school_id,$module)
{
  $this->db->select('*');
  $this->db->from('template_email');
  $this->db->where(array('school_id'=>1,'module'=>'student edit'));
  return $this->db->get()->row();

}
 function get_all_student($schoolId,$ids)
    {


     $this->db->select('student.email,student.mobile');
     // $this->db->order_by('id', 'desc');

     $this->db->from('map_school_student');
     $this->db->where(array('school_id'=>$schoolId,'student.id'=>$ids));
     $this->db->join('school', 'map_school_student.school_id=school.id', 'Left');
     $this->db->join('student', 'map_school_student.student_id=student.id', 'Left');
        // $this->db->join('authentication', 'authentication.student_id=student.id', 'Left');
     return $this->db->get()->result_array();
   }
function get_all_students($ids)
    {


     $this->db->select('student.email,student.mobile');
     // $this->db->order_by('id', 'desc');

     $this->db->from('student');
     $this->db->where('student.id',$ids);
     // $this->db->join('school', 'map_school_student.school_id=school.id', 'Left');
     // $this->db->join('student', 'map_school_student.student_id=student.id', 'Left');
        // $this->db->join('authentication', 'authentication.student_id=student.id', 'Left');
     return $this->db->get()->result_array();
   }
function data_sms($data)
{
   $this->db->insert('test',$data);
      return $this->db->insert_id();
}
function get_all_employee($data)
{

   $this->db->insert('test',$data);
      return $this->db->insert_id();
}
function get_all_employees($ids)
    {


     $this->db->select('*');
     // $this->db->order_by('id', 'desc');

     $this->db->from('employees');
     $this->db->where('employees.id',$ids);
     // $this->db->join('school', 'map_school_student.school_id=school.id', 'Left');
     // $this->db->join('student', 'map_school_student.student_id=student.id', 'Left');
        // $this->db->join('authentication', 'authentication.student_id=student.id', 'Left');
     return $this->db->get()->result_array();
   }
   function fetch_data($query)
 {
  // $this->db->like('student_name', $query);
  // $this->db->where("mobile like '%$query%'");
  $this->db->where("student_name like '%$query%'");
  $this->db->or_where("mobile like '%$query%'");
  $query = $this->db->get('student');
  if($query->num_rows() > 0)
  {
   foreach($query->result_array() as $row)
   {
    $output[] = array(
     'name'  => $row["student_name"],
     'email'  => $row["email"],
     'mobile'  => $row["mobile"]
     // 'image'  => $row["image"]
    );
   }
   echo json_encode($output);
  }
 }
   function GetRow($query) {        
        // $this->db->order_by('id', 'DESC');

     $this->db->select('student.student_name,student.mobile,authentication.username,student.id as student_id');

    

     $this->db->from('student');
     $this->db->join('authentication','student.id=authentication.user_id');
      $this->db->where("student_name like '%$query%'");
  $this->db->or_where("mobile like '%$query%'");
  $this->db->or_where("username like '%$query%'");
    // $query=$this->db->query("select * from student where email like '%$keyword'");
  return $this->db->get()->result_array();

        // $this->db->like("student_name", $keyword);
   // $this->db->where("student_name like '%$keyword%'");
        // return $query->result_array();
    }
    function insert_data($table_name,$params)
    {
      $this->db->insert($table_name,$params);
      return $this->db->insert_id();
    }
    function fetch_template_sms($school_id,$module)
    {
       $this->db->select('template_sms.context,template_sms.module,template_sms.id,map_school_sms_template.school_id');

    

     $this->db->from('map_school_sms_template');
      $this->db->where('map_school_sms_template.school_id',$school_id);
     $this->db->join('template_sms','template_sms.id=map_school_sms_template.template_id');
       $this->db->where('template_sms.module',"student add");
     return $query= $this->db->get()->row_array();
    
    }
}
?>