<?php
/* 
 * Generated by CRUDigniter v3.2 
 * www.crudigniter.com
 */
 
class Test_model extends CI_Model
{
    function __construct()
    {
        parent::__construct();
    }

    
    /*
     * Get subject by id
     */
     function get_student_count()
     {

        ##will improve
        $this->db->select('debit,id as ids');
       // $this->db->where('class_id',);
     $query=$this->db->get('account_transaction')->result();
      return $query;

}

function templatetest($school_id,$module)
{
  $this->db->select('*');
  $this->db->from('template_email');
  $this->db->where(array('school_id'=>1,'module'=>'student edit'));
  return $this->db->get()->row();

}
}
?>