<?php
/* 
 * Generated by CRUDigniter v3.2 
 * www.crudigniter.com
 */
 
class Trainer_model extends CI_Model
{
    function __construct()
    {
        parent::__construct();
    }
    
    /*
     * Get trainer by id
     */
    function get_trainer($id)
    {
        return $this->db->get_where('trainers',array('id'=>$id))->row_array();
    }
    
    /*
     * Get all trainers count
     */
    function get_all_trainers_count()
    {
        $this->db->from('trainers');
        return $this->db->count_all_results();
    }
        
    /*
     * Get all trainers
     */
    function get_all_trainers($params = array())
    {
        $this->db->order_by('id', 'desc');
        if(isset($params) && !empty($params))
        {
            $this->db->limit($params['limit'], $params['offset']);
        }
        return $this->db->get('trainers')->result_array();
    }
        
    /*
     * function to add new trainer
     */
    function add_trainer($params)
    {
        $this->db->insert('trainers',$params);
        return $this->db->insert_id();
    }
    
    /*
     * function to update trainer
     */
    function update_trainer($id,$params)
    {
        $this->db->where('id',$id);
        return $this->db->update('trainers',$params);
    }
    
    /*
     * function to delete trainer
     */
    function delete_trainer($id)
    {
        return $this->db->delete('trainers',array('id'=>$id));
    }
}
