<?php
/* 
 * Generated by CRUDigniter v3.2 
 * www.crudigniter.com
 */
 
class Student_model extends CI_Model
{
    function __construct()
    {
        parent::__construct();
    }
    
    /*
     * Get student by id
     */
    function get_student($id)
    {
        return $this->db->get_where('student',array('id'=>$id))->row_array();
    }
        
    /*
     * Get all student
     */
    function get_all_student()
    {
        $this->db->order_by('id', 'desc');
        return $this->db->get('student')->result_array();
    }
        
    /*
     * function to add new student
     */
    function add_student($params)
    {
        $this->db->insert('student',$params);
        return $this->db->insert_id();
    }
    
    /*
     * function to update student
     */
    function update_student($id,$params)
    {
        $this->db->where('id',$id);
        return $this->db->update('student',$params);
    }
    
    /*
     * function to delete student
     */
    function delete_student($id)
    {
        return $this->db->delete('student',array('id'=>$id));
    }

      function add_mapping($ids)
    {
        $this->db->insert('map_school_student',$ids);
        return $this->db->insert_id();
    }

      function get_authentication_id()
    
    {
      $this->db->from('master_authorization');
        return $this->db->get()->result();
    }

     function add_user($authentication)
     {
         $this->db->insert('authentication',$authentication);
        return $this->db->insert_id();
     }
      function fetch_classes($school_id)
    {
   
        $this->db->select('classes.name,classes.id');
        $this->db->from('map_school_class');
        $this->db->join('school', 'map_school_class.school_id=school.id', 'Left');
        $this->db->join('classes', 'map_school_class.class_id=classes.id', 'Left');
         $this->db->where('school_id',$school_id);
        return $query = $this->db->get()->result();
    }
    function add_mappingToClass($studentClassMapping)
    {
         $this->db->insert('map_student_class',$studentClassMapping);
        return $this->db->insert_id();
    }
    
   
}
?>